import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const skills = [
    { name: 'React', path: '/SKILLS/react.png' },
    { name: 'Microchip', path: '/SKILLS/microchip.png' },
    { name: 'Arduino', path: '/SKILLS/arduino.png' },
    { name: 'JavaScript', path: '/SKILLS/js.png' },
    { name: 'Nest js', path: '/SKILLS/nest.png' },
    { name: 'Git', path: '/SKILLS/git.png' },
    { name: 'MongoDB', path: '/SKILLS/mongodb.png' },
    { name: 'Figma', path: '/SKILLS/figma.png' },
    { name: 'Next js', path: '/SKILLS/nextjs.png' },
  ];

  const contactos = [
    { name: 'WhatsApp', path: '/social/whatsapp.png', url: "/" },
    { name: 'Linkedin', path: '/social/linkedin.png', url: "/" },
    { name: 'GitHub', path: '/social/github.png', url: "/" },
  ];

  const projects = [
    { name: 'Settings', path: '/projects/configuraciones.png', text: "Page of show devices of the buses", url: "/" },
    { name: 'Buses', path: '/projects/camiones.png', text: "Page of show devices of the buses", url: "/" },
    { name: 'Ads', path: '/projects/anuncios.png', text: "Page of show devices of the buses", url: "/" },
    { name: 'Domotica', path: '/projects/domotica.png', text: "Page of show devices of the buses", url: "/" },
  ]

  const allSkills = [
    {
      name: "Fronted", text: "", skills: [
        { name: 'Html', path: '/SKILLS/html.png' },
        { name: 'Css', path: '/SKILLS/css.png' },
        { name: 'JavaScript', path: '/SKILLS/js.png' },
        { name: 'React', path: '/SKILLS/react.png' },
        { name: 'Next js', path: '/SKILLS/nextjs.png' },
      ]
    },
    {
      name: "Backend", text: "", skills: [
        { name: 'JavaScript', path: '/SKILLS/js.png' },
        { name: 'Node js', path: '/SKILLS/nodejs.png' },
        { name: 'Nest js', path: '/SKILLS/nest.png' },
        { name: 'Mongo Db', path: '/SKILLS/mongodb.png' },
        { name: 'Postgres', path: '/SKILLS/postgres.png' },
      ]
    },
    {
      name: "IoT", text: "", skills: [
        { name: 'Arduino', path: '/SKILLS/arduino.png' },
        { name: 'C++', path: '/SKILLS/c++.png' },
        { name: 'Microchip', path: '/SKILLS/microchip.png' },
        { name: 'Raspberry', path: '/SKILLS/raspberry.png' },
      ]
    },
    {
      name: "Other", text: "", skills: [
        { name: 'Git', path: '/SKILLS/git.png' },
        { name: 'Linux', path: '/SKILLS/linux.png' },
        { name: 'Matlab', path: '/SKILLS/matlab.png' },
        { name: 'Figma', path: '/SKILLS/figma.png' },
        { name: 'Notion', path: '/SKILLS/notion.png' },
      ]
    },
  ]



  // ?------------------------------
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}


      <main className='min-h-screen'>

        {/* //?--------------------------------------------------------------- */}
        <section className='min-h-screen dark:bg-azul-negro sm:grid sm:grid-cols-2 mt-8   '>

          <div className='m-auto px-5 text-center md:text-start'>
            <h2 className='text-2xl my-3'>Hi 🖖,</h2>
            <h1 className='text-6xl font-bold '>{"I'm"} <span className='text-red-400'>Franck</span></h1>
            <h3 className='text-3xl my-3 font-semibold text-purple-900 dark:text-purple-500'>{'< Web Developer />'}</h3>
            <p className='text-gray-700 mb-8 dark:text-white text-xl'>
              Desarrollo de aplicaciones web, algoritmos, bases de datos y automatizacion de dispositivos.
            </p>
            <div className='flex items-center gap-8 justify-center md:justify-start'>
              {contactos.map((contact, index) => (
                <Button key={index}>
                  <Link href={contact.url} className='block justify-center '>
                    <Image
                      className='peer w-8 mx-auto'
                      src={contact.path}
                      alt={contact.name}
                      width={60}
                      height={60}
                    />
                    {/* <p>{contact.name}</p> */}
                  </Link>
                  {/* <p className='text-center mt-2 invisible peer-hover:visible'>{contact.name}</p> */}
                </Button>
              ))}

            </div>
          </div>


          <div className=" hidden sm:flex md:h-1/2 items-center hover:animate-born my-10 md:my-auto  ">
            <div className=" grid grid-cols-3 w-4/5 md:w-3/4 mx-auto gap-y-8  md:gap-y-16 " >
              {skills.map((skill, index) => (
                <div key={index}>
                  <Image
                    // Absolute URL                    
                    className='peer w-14 sm:w-18 animate-spin-slow hover:animate-none hover:scale-125 m-auto'
                    src={skill.path}
                    alt={skill.name}
                    width={77}
                    height={77}
                  />
                  <p className='text-center mt-2 invisible peer-hover:visible'>{skill.name}</p>
                </div>
              ))}

            </div>
          </div>

          <div className='flex justify-center items-center col-span-2 mb-12 my-12'>
            <Link href={"/contact"}>
              <Button className='bg-red-500 text-white px-6 text-lg '>Contact me!</Button>
            </Link>
          </div>

        </section>

        {/* //?--------------------------------------------------------------- */}

        <hr className=' my-8' />

        {/* //?------------- */}

        <section id='projects' className='mt-12'>
          <div>
            <h1 className='text-5xl font-bold text-center'>Portfolio</h1>
          </div>
          <div className='grid grid-cols-2 '>
            {projects.map((project, index) => (
              <div key={index} className=' relative  w-fit m-auto '>
                <Image
                  className=' w-48 sm:w-80 lg:w-96  m-auto hover:opacity-50 peer-hover:opacity-50 transition-all duration-300'
                  src={project.path}
                  alt={project.name}
                  width={500}
                  height={500}
                />
                <div className='peer sm:absolute  bottom-0  left-0 right-0 opacity-100 peer-hover:opacity-100 hover:opacity-100 m-4 grid transition-all duration-500'>
                  <p className=''>{project.text}</p>
                  <div className='flex justify-between'>
                    <h1 className='text-3xl'>{project.name}</h1>
                    <Link href={project.url}>
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6 hover:text-red-400 hover:scale-150">
                        <path fillRule="evenodd" d="M3.75 12a.75.75 0 01.75-.75h13.19l-5.47-5.47a.75.75 0 011.06-1.06l6.75 6.75a.75.75 0 010 1.06l-6.75 6.75a.75.75 0 11-1.06-1.06l5.47-5.47H4.5a.75.75 0 01-.75-.75z" clipRule="evenodd" />
                      </svg>
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className='flex justify-center items-center col-span-2 mb-12 my-12'>
            <Link href={"/contact"}>
              <Button className='bg-red-500 text-white px-6 text-lg '>More projects</Button>
            </Link>
          </div>
        </section>

        {/* //?--------------------------------------------------------------- */}

        <hr className=' my-8' />

        {/* //?------------- */}

        <section id='about'>
          <div className='grid md:grid-cols-2 my-8'>
            <div className='grid gap-y-8 my-8 mx-4 md:mx-0'>
              <h1 className='text-5xl font-bold tex'>About</h1>
              <p className='text-xl md:text-2xl'>Mi nombre es Francisco Angel Romero Tepal, trabajo en el mundo de la tecnología creando y dando vida a ideas.</p>
              <p className='text-xl md:text-2xl'>Soy Desarrollador Full-Stack con conocimientos en <b className='text-purple-900 dark:text-purple-500 font-semibold'> Frontend, Backend y IoT. </b> Desarrollo sitios web, aplicaciones web, herramientas para usuarios y dispositivos de IoT.</p>
            </div>
            <div className='m-auto '>
              <Image
                className='peer w-48 sm:w-80 lg:w-96  m-auto hover:opacity-50 peer-hover:opacity-50 transition-all duration-300'
                src="/mi_foto_pro.jpeg"
                alt="Imagen de Francisco Angel Romero Tepal"
                width={500}
                height={500}
              />
              <p className='text-xl text-center mt-2 invisible peer-hover:visible'>Francisco Angel Romero Tepal</p>
            </div>
          </div>

          <div className='grid md:grid-cols-2 gap-8'>
            <div className=' mx-4 md:mx-0'>

              <h1 className='text-4xl font-bold'>Experience</h1>
              <hr />
              <div className='p-4 m-4 border rounded-lg grid-3-4 '>
                <div>
                  <h3 className='text-2xl font-semibold'>Desarrollo de dispositivos y aplicaciones para IoT.</h3>
                  <p>Grupo Accesa</p>
                  <p>Current: Otoño 2021</p>
                </div>
                <div>
                  <Image
                    className='peer w-36 sm:w-48  hover:scale-125 m-auto'
                    src="/projects/anuncios.png"
                    alt="Grupo Accesa"
                    width={500}
                    height={500}
                  />
                </div>
              </div>
              <div className='p-4 m-4 border rounded-lg grid-3-4'>
                <div>
                  <h3 className='text-2xl font-semibold'>Desarrollo de dispositivos en IoT</h3>
                  <p>Laboratorio Sled</p>
                  <p>Sesson: Primavera 2019 - Otoño 2020</p>
                </div>
                <div>
                  <Image
                    className='peer w-36 sm:w-48  hover:scale-125 m-auto'
                    src="/projects/anuncios.png"
                    alt="Grupo Accesa"
                    width={500}
                    height={500}
                  />
                </div>
              </div>

              <h1 className='text-4xl font-bold'>Education</h1>
              <hr />
              <div className='p-4 m-4 border rounded-lg grid-3-4'>
                <div>
                  <h3 className='text-2xl font-semibold'>Platzi</h3>
                  <p>Grupo Accesa</p>
                  <p>Current: Otoño 2022</p>
                </div>
                <div>
                  <Image
                    className='peer w-36 sm:w-48  hover:scale-125 m-auto'
                    src="/projects/anuncios.png"
                    alt="Grupo Accesa"
                    width={500}
                    height={500}
                  />
                </div>
              </div>
              <div className='p-4 m-4 border rounded-lg grid-3-4'>
                <div>
                  <h3 className='text-2xl font-semibold'>Buap</h3>
                  <p>Grupo Accesa</p>
                  <p>Current: Otoño 2015 - Otoño 2020</p>
                </div>
                <div>
                  <Image
                    className='peer w-36 sm:w-48  hover:scale-125 m-auto'
                    src="/projects/anuncios.png"
                    alt="Grupo Accesa"
                    width={500}
                    height={500}
                  />
                </div>
              </div>

            </div>

            {/* // */}
            <div>
              <h1 className='text-4xl font-bold'>Skills</h1>
              <hr />
              <div className='grid gap-8 md:grid-cols-1'>
                {allSkills.map((data, index1) => (
                  <div key={index1} className='grid gap-y-8 '>
                    <h1 className='text-3xl font-semibold italic m-4 '>{data.name}</h1>
                    <div className='grid grid-auto gap-y-8 w-4/5 m-auto'>
                      {data.skills.map((skill, index) => (
                        <div key={index}>
                          <Image
                            className='peer w-10 sm:w-12 animate-spin-slow hover:animate-none hover:scale-125 m-auto'
                            src={skill.path}
                            alt={skill.name}
                            width={77}
                            height={77}
                          />
                          <p className='text-center mt-2 invisible peer-hover:visible'>{skill.name}</p>
                        </div>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>

          </div>


        </section>


        {/* //?--------------------------------------------------------------- */}

        <hr className=' my-8' />

        {/* //?------------- */}


        <section id='about'>
          <h1>Services</h1>
        </section>

        {/* //?--------------------------------------------------------------- */}

        <hr className=' my-8' />

        {/* //?------------- */}

        <section id='contact'>
          <h1>Contact</h1>
        </section>
      </main>

    </>
  )
}
