import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@/components/Button'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const skills = [
    { name: 'React', path: '/SKILLS/react.png' },
    { name: 'Microchip', path: '/SKILLS/microchip.png' },
    { name: 'Arduino', path: '/SKILLS/arduino.png' },
    { name: 'JavaScript', path: '/SKILLS/js.png' },
    { name: 'Nest js', path: '/SKILLS/nest.png' },
    { name: 'Git', path: '/SKILLS/git.png' },
    { name: 'MongoDB', path: '/SKILLS/mongodb.png' },
    { name: 'Figma', path: '/SKILLS/figma.png' },
    { name: 'Next js', path: '/SKILLS/nextjs.png' },
  ];

  const contactos = [
    { name: 'WhatsApp', path: '/social/whatsapp.png', url: "/" },
    { name: 'Linkedin', path: '/social/linkedin.png', url: "/" },
    { name: 'GitHub', path: '/social/github.png', url: "/" },
  ];
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}


      <main className='min-h-screen'>

        <section className=' dark:bg-azul-negro md:grid grid-cols-2 mt-8   '>

          <div className='m-auto px-5 '>
            <h2 className='text-2xl my-3'>Hi 🖖,</h2>
            <h1 className='text-6xl font-bold '>{"I'm"} <span className='text-red-400'>Franck</span></h1>
            <h3 className='text-3xl my-3 font-semibold text-purple-900 dark:text-purple-500'>{'< Web Developer />'}</h3>
            <p className='text-gray-700 mb-8 dark:text-white'>
              Desarrollo de aplicaciones web, algoritmos, bases de datos y automatizacion de dispositivos.
            </p>
            <div className='flex items-center gap-8'>
              {contactos.map(contact => (
                <Button key={0}>
                  <Link href={contact.url} >
                    <Image
                      key={0}
                      className='w-8 '
                      src={contact.path}
                      alt={contact.name}
                      width={60}
                      height={60}
                    />
                    {/* <p>{contact.name}</p> */}
                  </Link>
                </Button>
              ))}

            </div>
          </div>


          <div className=" md:h-1/2 flex items-center hover:animate-born my-10 md:my-auto  ">
            <div className=" grid grid-cols-3  md:w-3/4 mx-auto  md:gap-y-16 " >
              {skills.map(skill => (
                <div>
                  <Image
                    // Absolute URL
                    key={0}
                    className='peer w-14 sm:w-18 animate-spin-slow hover:animate-none hover:scale-125 m-auto'
                    src={skill.path}
                    alt={skill.name}
                    width={77}
                    height={77}
                  />
                  <p className='text-center mt-2 invisible peer-hover:visible'>{skill.name}</p>
                </div>
              ))}

            </div>
          </div>

          <div className='flex justify-center items-center col-span-2 mb-12'>
            <Link href={"/contact"}>
              <Button className='bg-red-500 text-white px-6 text-lg '>Contact me!</Button>
            </Link>
          </div>

        </section>

        {/* //?------------- */}

        <hr />
        <section id='projects'>
          <div>
            <h1 className='text-6xl font-bold '>Projects</h1>
          </div>
        </section>

        {/* <section id='proyects'>
          <div className="relative">
            <Image
              // Absolute URL
              className='m-auto hover:backdrop-filter'
              src='/mi_foto_pro.jpeg'
              alt='User profile picture'
              width={300}
              height={300}
            />
            <div className="absolute top-0 left-0 right-0 bottom-0 flex flex-col items-center justify-center text-center text-white transition-all duration-300 opacity-0 hover:opacity-100">
              <h2 className="text-lg font-bold">Título de la imagen</h2>
              <p className="text-sm">Descripción de la imagen</p>
            </div>
          </div>
        </section> */}


      </main>

      {/* <div className='fixed top-3/4 left-1/2 justify-center col-span-2 border'>
        <Button className='bg-red-500 text-white px-6 text-lg mt-5'>Contact me!</Button>
      </div> */}
    </>
  )
}
